[tool.poetry]
name = "filter"
version = "0.1.0"
description = "project for educational purposes"
authors = ["Roman Bolkhovitin <rbolkhovitin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
pymorphy2 = "^0.8.0"
beautifulsoup4 = "^4.8"
cchardet = "^2.1"
aiodns = "^2.0"
aionursery = "^0.3.0"
async-timeout = "^3.0"
aiohttp-cache = {git = "https://github.com/cr0hn/aiohttp-cache.git", rev = "9670a3d42ccadd959ec460e2a4e20bfa01ffa295"}
aioredis = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-asyncio = "^0.10.0"
mypy = "^0.750.0"
flake8 = "^3.7"
pytest-aiohttp = "^0.3.0"
pytest-cov = "^2.8"

[tool.poetry.scripts]
serve = "filter.server.server:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
