version: "3"
services:
  filter:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      FILTER_REDIS_HOST: "redis"
    ports:
    - "8080:8080"

  redis:
    image: redis:5
