name: News Filter

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install-dev
    - name: Lint with flake8
      run: |
        make lint
    - name: Check typing with mypy
      run: |
        make mypy
    - name: Test with pytest
      run: |
        make tests-cov
